packages:
  # all packages in direct subdirs of packages/
  # - 'source/patterns/@csdc-solutions-constructs/*'
  - 'source/patterns/@tyyzqmf/*'
  # - 'source/examples/*'
  # exclude packages that are inside test directories
  - '!**/test/**'